config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :shops

  root 'bikes#index'
  get '/home' => 'bikes#index'
  get '/login' => 'users#login'
  get '/register' => 'users#register'
  post '/sessions' => 'sessions#create'
  post '/users' => 'users#create'
  get '/users/login' => 'users#login'
  get '/users/register' => 'users#register'
  get 'Logout' => 'bikes#logout'
  get '/shop' => 'shops#index'
  get '/contacts' => 'contacts#index'
  get 'shop' => 'shops#new'
  get 'edit' => 'shops#edit'
  get 'delete' => 'shops#delete'
  get '/search' => 'shops#search'
  get 'update' => 'shops#update'
  get 'basket' => 'shops#basket'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController

    def index
        
    end

    def logout     
        session[:user_id] = nil     
        redirect_to '/home' 
    end  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        user = User.find_by(email:login_params[:email])
        if user && user.authenticate(login_params[:password])
            session[:user_id] = user.id
            redirect_to '/home'
        elsif user && user.authenticate(login_params[:password]) && user.adminrights=="true"
                redirect_to '/home'	
                session[:user_id] = user.id
        else
            flash[:login_errors] = ['invalid credentials']
            redirect_to '/login'
        end
    end

    private
        def login_params
            params.require(:login).permit(:email, :password) 
        end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
    

    def shop
        
    end


end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

    def show

    end

    def index
        @Shop = Shop.all
    end
    
    def new
        @Shop = Shop.new
    end

    def edit
        @Shop = Shop.find(params[:id])
    end

    def delete
        @Shop = Shop.find(params[:id])
        @Shop.destroy
        redirect_to action:"index"
    end

    def update
        @Shop = Shop.find(params[:id])
        @Shop.assign_attributes(shop_params)
        if @Shop.valid?
            @Shop.save
        flash[:notice] = "Updated"
        redirect_to action:"index"
        else
            flash[:notice] = "Update failed"
            redirect_to action:"index"
            end
        
    end

    def search
        @Shop = Shop.where("title LIKE?", "%" +params[:q] + "%")
        render "index"
    end

    def shop_params
        params.require(:shop).permit(:title,:biketypes,:gearquantity,:price)	
    end

    def basket

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def main_page

    end

    def login

    end

    def register

    end



    def create
        user = User.new(user_params)
        if user.save
            session[:user_id] = user.id
            redirect_to '/home'
        else
            flash[:register_errors] = user.errors.full_messages
            redirect_to '/home'
        end

    end


    private
        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
        end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bikes/index.html.erb
<div class="home_page">


<h1>Welcome to bikeshop!</h1>
</body>
</html>

</div>
<div class="thick">
<p>You can buy various types of bikes here! Head over to the shop to start buying!</p>
</div>

app/views/contacts/index.html.erb
<div class="home_page">


<h1>Contacts</h1>
</body>
</html>

</div>
<div class="thick">
<p>Edgaras: https://github.com/Edgaras44</p>
<p>Mantas: https://github.com/Mantas83</p>
<p>Džiugas: https://github.com/s034745</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bikeshop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
body  {
  background-image: url("https://wallpaperaccess.com/full/333369.jpg");
}
</style>
  </head>

<br>
<div class="main_buttons">
<%= link_to "Home", home_path %>
  <a href="shop">Shop</a>
<%= link_to "Contacts", contacts_path %>
</div>
<footer>
<% if session[:user_id].nil? %>
      <%= link_to "Login", users_login_path %>
  	  <%= link_to "Register", users_register_path %>
      <% else %>
      <% @user=User.find(session[:user_id]) %>
       Logged in  as :<%=@user.name %>
          <br>
          <% if @user.adminrights=="true" %>
          ADMIN
          <% end %>
       <br>
      <%= link_to "Log out",:controller => :bikes, :action => :logout %>
<% end %>
</footer>
<br>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shops/basket.html.erb
Neveikia

app/views/shops/edit.html.erb
<%= form_for @Shop, url:{action: "update"} do|e| %>
<p>
	<%= e.label :title %>
	<%= e.text_field :title %>
</p>
<p>
 	<%= e.label :biketypes %>
	<%= e.text_field :biketypes %>
</p>
<p>
	<%= e.label :gearquantity %>
	<%= e.text_area :gearquantity %>
</p>
<p>
	<%= e.label :price %>
	<%= e.text_area :price %>
</p>
<%= e.submit("Update")%>
<% end %>

app/views/shops/index.html.erb
<form class="form-inline my-2 my-lg=0" action="/search">
	<input class="form-control mr-sm-2" name="q" type="text" placeholder="Search" aria-label="Search">
	<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
<div class="normal">
<table border="1" width="800" cellpadding="1" cellspacing="1">
	<thread>
		<th>Title</th>
		<th>Type</th>
		<th>Gear quantity</th>
        <th>Price</th>
		<% if session[:user_id].present? %>
		<th>Add to basket</th>
		<% @user=User.find(session[:user_id]) %>
		<% if @user.adminrights=="true" %>
		<th colspan="2">Action</th>
		<% end %>
		<% end %>
	</thread>
	<tbody>
    <% @Shop.each do |f|%>
	<tr>
		<td><%= f.title %></td>
		<td><%= f.biketypes %></td>
		<td><%= f.gearquantity %></td>
        <td><%= f.price %></td>
		<% if session[:user_id].present? %>
		<% @user=User.find(session[:user_id]) %>
		<td><%= link_to "add" , :controller => :shops,:action => :basket ,id:f.id %></td>
		<% if @user.adminrights=="true" %>
<td><%= link_to "edit" , :controller => :shops,:action => :edit ,id:f.id %></td>

<td>
	<%= link_to "delete" ,:controller => :shops, :action => :delete ,id:f.id %>
		
	</td>
	</tr>
	<% end %>
	<% end %>
<% end %>



	</tbody>
</table>
</div>

app/views/shops/search.html.erb
<h1>Results</h1>

app/views/users/login.html.erb
<div class="normal">
<h1>Login </h1>

<form action="/sessions" method="POST">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <input type="email" name="login[email]" placeholder="email">
    <input type="password" name="login[password]" placeholder="password">
    <input type="submit" name="submit" class="submit">
</form>

<div class="errors">
    <% if flash[:login_errors]%>
        <% flash[:login_errors].each do |error| %>
            <p> <%=error%></p>
        <%end%>
    <%end%>
</div>
</div>

app/views/users/register.html.erb
<div class="normal">
<h1>Registration<h1>

<form action="/users" method="POST">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <input type="name" name="user[name]" placeholder="name">
    <input type="email" name="user[email]" placeholder="email">
    <input type="password" name="user[password]" placeholder="password">
    <input type="password" name="user[password_confirmation]" placeholder="password_confirmation">
    <input type="submit" name="submit" class="submit">
</form>

<div class="errors">
    <% if flash[:register_errors]%>
    <% flash[:register_errors].each do |error| %>
        <p> <%=error%></p>
    <%end%>
<%end%>
</div>
</div>